### ISSUE TITLE
GitHub Actions on multiple os

### ISSUE THREAD

**Issue by slawekjaranowski** [kokuwaio/helm-maven-plugin#364]
**Is this a request for help?**: no

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**What happened**:
GitHub Actions only use linux for build - is it intensional? 

**What you expected to happen**:
use linux, windows and macos

**Anything else we need to know**:
If no objection I can try to do it ....

**Comment by sschnabe** [comment]
For PR build linux/windows/macos were used for pull requests. I've disabled the macos runner because they where unstable and testing the Gitlab integration failed regularly. On main the build is done on linux only because from my point of view the resulting jar would be exacly the same.

An action point i see is to reevaluate if macos runner are still blocked by Github, or exclude tests using Github API.

**Comment by slawekjaranowski** [comment]
@sschnabe - thanks
